name: Request on pull request  # 👈 Fixed: "name" should not have a colon after it

on:
  pull_request:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Node.js (reads version from .nvmrc)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"  # Ensure .nvmrc exists in your repo!

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

        # Start the project (optional: only for testing)
      - name: test
        run: npm run test

      # Start the project (optional: only for testing)
      - name: Build app
        run: npm run build


